--output '%(uploader)s - %(title)s - %(extractor)s-%(id)s.%(ext)s'
--trim-filenames 180
--write-info-json
--write-subs
--write-auto-subs
<<<<<<< HEAD
--convert-subs 'srt'
--sub-langs 'en,fr'
--embed-chapters
>>>>>>> a38c1bd9 (Sync with https://gitlab.com/nodiscc/debian-live-config branch 5.0.0)
--restrict-filenames
--compat-options no-live-chat
#--add-metadata
